### ISSUE TITLE
More data in the smiling dataset

### ISSUE THREAD

**Issue by zeina-abuaisheh** [raulorteg/SmileCVAE#1]
Hello,

Thanks for making your code public.
I am interested in the smiling dataset you are using, I know that you took some images from the UTKFace dataset:
https://github.com/raulorteg/SmileCVAE/blob/master/datasets/smiles_dataset.txt
Did you label more images? I am interested in having much more data than the ones above.

Thanks

**Comment by raulorteg** [comment]
Hi!
Sorry, I did have more manualy labelled data but I lost it in another computer, Im sorry. I can however share how I created the labels of the smile degree, I hope you can find it useful.

Please let me know if I can help, my email is mail.raulorteg@gmail.com
Thanks

[Generative_Models_report-6-7.pdf](https://github.com/raulorteg/SmileCVAE/files/9055389/Generative_Models_report-6-7.pdf)
